"""initial schema

Revision ID: 0e25894e177a
Revises: 
Create Date: 2026-07-01 03:35:57.689709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e25894e177a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('general', 'specialized', name='indicator_section'), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('unit_supervisor', 'hr', 'deputy', 'ceo', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], name='fk_users_personnel_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('org_unit', sa.String(length=150), nullable=False),
    sa.Column('contract_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='personnel_status'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_code')
    )
    op.create_table('evaluation_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('unit_supervisor_user_id', sa.Integer(), nullable=True),
    sa.Column('deputy_user_id', sa.Integer(), nullable=False),
    sa.Column('ceo_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ceo_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deputy_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['unit_supervisor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_code', sa.String(length=50), nullable=False),
    sa.Column('subject_personnel_id', sa.Integer(), nullable=False),
    sa.Column('unit_supervisor_user_id', sa.Integer(), nullable=True),
    sa.Column('deputy_user_id', sa.Integer(), nullable=False),
    sa.Column('ceo_user_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('supervisor_scoring', 'hr_review', 'deputy_review', 'ceo_final', name='evaluation_stage'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'hr_approved', 'deputy_approved', 'finalized', name='evaluation_status'), nullable=False),
    sa.Column('general_score_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('specialized_score_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_weighted_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('evaluator_comment', sa.Text(), nullable=True),
    sa.Column('final_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ceo_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deputy_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['unit_supervisor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_record_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluation_record_id'], ['evaluation_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_record_id', sa.Integer(), nullable=False),
    sa.Column('commenter_user_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('hr_review', 'deputy_review', 'ceo_final', name='comment_stage'), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commenter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluation_record_id'], ['evaluation_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_record_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='ck_evaluation_scores_score_range'),
    sa.ForeignKeyConstraint(['evaluation_record_id'], ['evaluation_records.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_scores')
    op.drop_table('evaluation_comments')
    op.drop_table('audit_log')
    op.drop_table('evaluation_records')
    op.drop_table('evaluation_access')
    op.drop_table('personnel')
    op.drop_table('users')
    op.drop_table('indicators')
    # ### end Alembic commands ###
